export enum LessonType {
  LECTURE = 'LECTURE',
  SEMINAR = 'SEMINAR',
  PRACTICE_SEMINAR = 'PRACTICE_SEMINAR',
  EXAM = 'EXAM',
  CONTROL_OF_SELF_WORK = 'CONTROL_OF_SELF_WORK',
  LABORATORY = 'LABORATORY',
}
